# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

include:
  - local: .gitlab/common.yml
  - local: .gitlab/sw-tests.yml

default:
  interruptible: true

stages:
  - init
  - build
  - run

# Sources the environment variables for the IIS environment
.init-env:
  before_script:
    # Hard link cached python packages since the UV cache directory
    # is configured to be on the same filesystem as the build directory in the CI.
    - export UV_CACHE_DIR=$CI_BUILDS_DIR/../cache/uv
    - export UV_LINK_MODE=hardlink
    - source iis-env.sh

##################
# Initialization #
##################

init-deps:
  stage: init
  extends:
    - .init-env
    - .init-deps-tpl
  artifacts:
    paths:
      - pd/ci.yml

########################################
# Generate RTL Sources and Addressmaps #
########################################

generate-rtl:
  stage: build
  extends:
    - .generate-rtl-tpl

########################
# Build Software Tests #
########################

sn-sw:
  stage: build
  extends:
    - .sn-sw-tpl

chs-sw:
  stage: build
  extends:
    - .chs-sw-tpl

#####################
# Build Simulations #
#####################

vsim-compile:
  stage: build
  extends:
    - .cache-deps
    - .init-env
  needs:
    - generate-rtl
  extends:
    - .init-env
  script:
    - make vsim-compile | tee compile.log 2>&1
    - '! grep "\*\* Error" compile.log'
  artifacts:
    paths:
      - target/sim/vsim/work
    expire_in: 2 day

vcs-compile:
  stage: build
  extends:
    - .cache-deps
    - .init-env
  needs:
    - generate-rtl
  script:
    - make vcs-compile-batch | tee compile.log 2>&1
    - '! grep "Error-\[" compile.log'
  artifacts:
    paths:
      - target/sim/vcs/build
    expire_in: 2 day

###################
# Run simulations #
###################

sim-vsim:
  stage: run
  extends:
    - .cache-deps
    - .init-env
    - .sw-tests
  variables:
    LOG_FILE: transcript
  needs:
    - chs-sw
    - sn-sw
    - vsim-compile
  script:
    - make vsim-run-batch-verify
    - !reference [.check-simulation, script]
  artifacts:
    paths:
      - ${LOG_FILE}

sim-vcs:
  stage: run
  extends:
    - .cache-deps
    - .init-env
  variables:
    LOG_FILE: transcript
    CHS_BINARY: sw/cheshire/tests/simple_offload.spm.elf
    SN_BINARY: sw/snitch/apps/mha/build/mha.elf
    VERIFY_PY: .deps/snitch_cluster/sw/kernels/dnn/mha/scripts/verify.py
    PRELMODE: 3
  needs:
    - chs-sw
    - sn-sw
    - vcs-compile
  script:
    # Run the VCS simulation and capture the console output into a log file
    - make vcs-run-batch-verify 2>&1 | tee ${LOG_FILE}
    - !reference [.check-simulation, script]
  artifacts:
    paths:
      - ${LOG_FILE}

#####################
# Run Experiments   #
#####################

sim-exps:
  stage: run
  extends:
    - .cache-deps
    - .init-env
  needs:
    - chs-sw
    - sn-sw
    - vsim-compile
  parallel:
    matrix:
      - EXPERIMENT: multicast
      - EXPERIMENT: reduction
      - EXPERIMENT: barrier
  script:
    - cd experiments/$EXPERIMENT && ./experiments.py --ci --actions sw run -j
  artifacts:
    expire_in: 2 days

###################
# Physical Design #
###################

subpipe:
  stage: build
  interruptible: true
  needs:
    - init-deps
  trigger:
    include:
      - artifact: pd/ci.yml
        job: init-deps
    strategy: depend
