#!/usr/bin/env python3
# Copyright 2026 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
import argparse
import sys
from pathlib import Path
from pysynthutils import LintViolations


WAIVERS = [
    # unsigned argument passed to $unsigned system function
    'WRN_1024',
    # flop enable pin is constant
    'FlopEConst',
    # operand width mismatch across arithmetic/comparison operators
    'W116',
    # input declared but not read
    'W240',
    # instance output port left unconnected
    'W287b',
    # operand width mismatch across relational operators
    'W362',
    # signal assigned multiple times in the same always block
    'W415a',
    # based number literal contains don't-care (?), sim/synth mismatch risk
    'W467',
    # shift result wider than LHS truncates bits
    'W486',
    # variable assigned but never read
    'W528'
]
TILES_DIR = Path(__file__).parent / 'build'
TOP = 'gwaihir_top'

IMPLICIT_MACROS = [
    'TARGET_FLIST',
    'TARGET_RTL',
    'TARGET_CVA6',
    'TARGET_CV64A6_RT_HPDCACHE',
    'TARGET_GW_GEN_RTL',
    'TARGET_MXCORE_HWPE',
    'TARGET_TECH_CELLS_GENERIC_INCLUDE_TC_SYNC'
]


def tile_files(tile, tiles_dir):
    """Return the set of source files reachable from the `tile` top module.

    The file lists are generated by `bender script flist-plus --top <tile>`
    (generated by `make spyglass-<tile>`), so they follow the actual module hierarchy.
    A file shared by several tiles belongs to all of them. The pseudo-tile
    `gwaihir_top` selects the files only the top level needs.
    """
    def read(name):
        with open(tiles_dir / f'{name}.f') as f:
            return {str(Path(line.strip()).resolve()) for line in f
                    if line.strip() and not line.startswith('+')}

    if tile != TOP:
        return read(tile)
    others = set().union(*(read(f.stem) for f in tiles_dir.glob('*.f') if f.stem != TOP))
    return read(TOP) - others


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('report', help='Path to moresimple.rpt')
    parser.add_argument('--tile', help='Only report violations in files reachable from this tile '
                                       'top module (e.g. cluster_tile), or in files only the top '
                                       f'level needs ({TOP}). Default: report everything.')
    parser.add_argument('--tiles-dir', type=Path, default=TILES_DIR,
                        help='Directory with the per-tile file lists <tile>.f')
    args = parser.parse_args()

    # Parse report for violations
    df = LintViolations(args.report).df
    print(f'Read {len(df)} violations.')

    # Ignore all info messages (Severity == Info)
    df = df[df.severity != 'Info']
    print(f'Ignore info messages. {len(df)} messages remaining.')

    # Ignore overlapping conditions in decoder's unique case statement
    # (ignore SYNTH_12604 in snitch.sv and snitch_sequencer.sv)
    # TODO(colluca): do not ignore sequencer error
    df = df[~((df.rule == 'SYNTH_12604') &
              (df.file.str.contains(r'snitch(?:_sequencer)?\.sv')))]
    print(f'Ignore SYNTH_12604 in snitch and snitch_sequencer. {len(df)} messages remaining.')

    # Ignore the width mismatch between the case labels and the selector in the FlooNoC reduction
    # arbiter. The labels are the (narrower) reserved opcodes: SystemVerilog zero-extends them to
    # the selector width, so the comparison is correct.
    df = df[~((df.rule == 'W263') &
              (df.file.str.contains(r'floo_reduction_arbiter\.sv')))]
    print(f'Ignore W263 in floo_reduction_arbiter. {len(df)} messages remaining.')

    # Waive unused macro warnings for macros created implicitly by bender
    df = df[~((df.rule == 'CMD_define02') &
              (df.message.str.contains('|'.join(IMPLICIT_MACROS))))]
    print(f'Waive CMD_define02 for {", ".join(IMPLICIT_MACROS)}. {len(df)} messages remaining.')

    # Waive safe to ignore rules
    df = df[~df.rule.isin(WAIVERS)]
    print(f'Waive {", ".join(WAIVERS)}. {len(df)} messages remaining.')

    # Restrict to the files owned by the requested tile
    if args.tile:
        files = tile_files(args.tile, args.tiles_dir)
        df = df[df.file.map(lambda f: str(Path(f).resolve()) in files)]
        print(f'Keep only violations in tile {args.tile}. {len(df)} messages remaining.')

    # Fail on remaining messages
    if len(df) > 0:
        print(f'FAIL: {len(df)} violation(s) found')
        # Print remaining messages
        for _, v in df.iterrows():
            print(f'  [{v.severity}] {v.rule}  {v.file}:{v.line}  {v.message}')
        sys.exit(1)
    print('PASS')


if __name__ == '__main__':
    main()
