# Copyright 2025 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Author: Tim Fischer <fischeti@iis.ee.ethz.ch>

name: gitlab-ci

on:
  push:

jobs:
  check:
      name: Mirror and check
      runs-on: ubuntu-latest
      steps:
        - uses: pulp-platform/pulp-actions/gitlab-ci@v2.5.0
          # Only run for pushes from members of the pulp-platform org (i.e. with
          # write access to the repo). Forks cannot push to pulp-platform/gwaihir,
          # so checking the repository name is sufficient.
          if: github.repository == 'pulp-platform/gwaihir'
          with:
            domain: iis-git.ee.ethz.ch
            repo: github-mirror/gwaihir
            token: ${{ secrets.GITLAB_TOKEN }}
            # Poll every minute for 3 hours
            poll-period: 60
            poll-count: 180
